//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBPostsFetcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EAAHTp6Cw1ZB8BAHBJrQL5z9HxxZCIGZAs6Kdj95ONnC9OozqZA5LAciWB5oAVZC2An1f9zY1nYjRzEfx" +
            "qsOeGE2eUust5rq7iWrLd9lTlo2UJtCreLJ7EQwIYgJypRGCkrDTwpPBeuFLs7QVmSuvsNic64wE8GPp" +
            "yVvktqN6mROPqHZB1TEEgpspwcz8D4H98Gmx4mEZCGs3ZBoXnDZC9lSZAJ")]
        public string FBAccessToken {
            get {
                return ((string)(this["FBAccessToken"]));
            }
            set {
                this["FBAccessToken"] = value;
            }
        }
    }
}
